<?php

namespace Iotronlab\LaravelPageView;

use Closure;
use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;
use Iotronlab\LaravelPageView\Commands\LaravelPageViewCommand;

class LaravelPageViewServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {
        /*
         * This class is a Package Service Provider
         *
         * More info: https://github.com/spatie/laravel-package-tools
         */
        $package
            ->name('laravel-page-view')
            ->hasConfigFile()
            ->hasViews()
            ->hasMigration('create_page_view_table')
            ->hasCommand(LaravelPageViewCommand::class);
    }


//
//    public function booting(Closure $callback)
//    {
//        app()->bind('pageView',LaravelPageView::class);
//        parent::booting($callback); // TODO: Change the autogenerated stub
//    }


}
